### ISSUE TITLE
Magenta groove with E-GMD dataset?

### ISSUE THREAD

**Issue by jeremydeanw** [magenta/magenta-studio#51]
Is there a version of groove that is trained on the current expanded midi dataset? 
https://magenta.tensorflow.org/datasets/e-gmd

**Comment by cghawthorne** [comment]
E-GMD adds more audio by synthesizing on an expanded set of drum kits, but it doesn't add any more symbolic drum information (which is what the Groove plugin trains on), so there isn't any need to retrain the Groove plugin.
