### ISSUE TITLE
Support Ableton Live 11

### ISSUE THREAD

**Issue by tmc** [magenta/magenta-studio#95]
<img width="558" alt="Screenshot 2023-08-05 at 1 32 35 AM" src="https://github.com/magenta/magenta-studio/assets/3977/3ad49b23-e4ed-43c5-a0f7-fe4bea97f3a0">

**Comment by elaurentin** [comment]
Is this completed? I am getting the same error. Ableton Live 11 Lite or only Ableton Max is supported.
